spring:
    application:
        name: Dungeon_And_Dilemmas
    liquibase:
        enabled: false
        change-log: classpath:db/changelog/db.changelog-master.xml
    datasource:
        url: jdbc:postgresql://localhost:5432/Dungeon_And_Dilemmas
        username: postgres
        password: 12345
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true

jwt:
    secret:
        access: dmVyeS1zdHJvbmctc2VjcmV0LWZvci1hY2Nlc3MtdG9rZW4tMDAx
        refresh: dmVyeS1zdHJvbmctc2VjcmV0LWZvci1yZWZyZXNoLXRva2VuLTAwMg==
    lifetime:
        access-minutes: 500
        refresh-days: 30