spring:
    application:
        name: Dungeon_And_Dilemmas
    liquibase:
        enabled: false
        change-log: classpath:db/changelog/db.changelog-master.xml
    datasource:
        url: jdbc:postgresql://localhost:5432/Dungeon_And_Dilemmas
        username: postgres
        password: 12345
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true